### PR TITLE
URA-337 helios vep config v1.2.0 

### PR DESCRIPTION
**Pull request by Aisha-D**
Revert back to VEP105

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)* status: all files reviewed, 7 unresolved discussions (waiting on @Aisha-D)

___
*[`tso500_vep_config_v1.2.0.json` line 8 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-mWN5-5EEo59TkRnd:-Ng-mWN5-5EEo59TkRne:bk19nhh) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L8)):*
> ```JSON
>     },
>         "vep_resources":{
>         "vep_docker":"file-G8V2Vz0433Gp5bYPF2f6vg9X",
> ```

105 - checked



_Code quote:_
```JSON
file-G8V2Vz0433Gp5bYPF2f6vg9X
```
___
*[`tso500_vep_config_v1.2.0.json` line 9 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-mf3T1HT8rQIIuY0S:-Ng-mf3U0QiBFYHOk5Ac:bk19nhh) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L9)):*
> ```JSON
>         "vep_resources":{
>         "vep_docker":"file-G8V2Vz0433Gp5bYPF2f6vg9X",
>         "vep_cache":"file-G8V4bGj433Gz96K3Fb1VfbG3",
> ```

105 - checked



_Code quote:_
```JSON
file-G8V4bGj433Gz96K3Fb1VfbG3
```
___
*[`tso500_vep_config_v1.2.0.json` line 10 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-mi557cQgMeFAWsON:-Ng-mi557cQgMeFAWsOO:bk19nhh) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L10)):*
> ```JSON
>         "vep_docker":"file-G8V2Vz0433Gp5bYPF2f6vg9X",
>         "vep_cache":"file-G8V4bGj433Gz96K3Fb1VfbG3",
>         "plugin_config":"file-G9jZpk8433GvFvX14P775324",
> ```

105 - checked



_Code quote:_
```JSON
file-G9jZpk8433GvFvX14P775324
```
___
*[`tso500_vep_config_v1.2.0.json` line 63 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-ml4FEPiZI50JTA_P:-Ng-ml4FEPiZI50JTA_Q:bk19nhh) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L63)):*
> ```JSON
>     {
>         "name": "SpliceAI",
>         "pm_file": "file-G8YXQQQ4jKX4bVz53zK7VJX5",
> ```

105 - checked



_Code quote:_
```JSON
file-G8YXQQQ4jKX4bVz53zK7VJX5
```
___
*[`tso500_vep_config_v1.2.0.json` line 81 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-mtL1CCxwYrRvooCF:-Ng-mtL1CCxwYrRvooCG:bk19nhh) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L81)):*
> ```JSON
>       {
>         "name": "REVEL",
>         "pm_file": "file-G9b5pxQ4jKXGP22y4byPpqq8",
> ```

105 - checked



_Code quote:_
```JSON
file-G9b5pxQ4jKXGP22y4byPpqq8
```
___
*[`tso500_vep_config_v1.2.0.json` line 92 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-n19B7cTWc3yr0Jkg:-Ng-n19B7cTWc3yr0Jkh:bk19nhh) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L92)):*
> ```JSON
>       {
>         "name": "Mastermind",
>         "pm_file": "file-G9bv2Fj433GbZ6z64Qk2G5VG",
> ```

105 - checked



_Code quote:_
```JSON
file-G9bv2Fj433GbZ6z64Qk2G5VG
```
___
*[`tso500_vep_config_v1.2.0.json` line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-nFV73ZLpKKwEQ-u7:-Ng-nFV73ZLpKKwEQ-u8:b-k8t7pv) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L103)):*
> ```JSON
>       {
>         "name": "CADD",
>         "pm_file": "file-G6BYQGQ433Gg0KfZF5xPfv1X",
> ```

104 - was this previously deemed okay to use with 105?



_Code quote:_
```JSON
file-G6BYQGQ433Gg0KfZF5xPfv1X
```

**Review by Aisha-D — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)* status: all files reviewed, 7 unresolved discussions (waiting on @mattgarner)

___
*[`tso500_vep_config_v1.2.0.json` line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-nFV73ZLpKKwEQ-u7:-Ng00UP5A034sZi-p0wl:baql9qc) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L103)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

104 - was this previously deemed okay to use with 105?
</blockquote></details>

Well.... when comparing this branch to the last release on vep 105 - everything but clinvar matched: https://github.com/eastgenomics/eggd_vep_helios_config/compare/v1.0.2...URA-337-helios-vep-config-v-1-2-0

On top of that, there appears to be no CADD 105 on dnanexus: https://platform.dnanexus.com/projects/Fkb6Gkj433GVVvj73J7x8KbV/data/assets/vep/vep_docker_v105.0

So it seems 104 was always used and it does populate data:



_Code snippet:_
```JSON
$ dx cat file-GZFGBzj45zqGPbPXxJFv3Xxf | zcat | grep "CSQ" | head -n 2
##INFO=<ID=CSQ,Number=.,Type=String,Description="Consequence annotations from Ensembl VEP. Format: Allele|SYMBOL|Consequence|IMPACT|EXON|INTRON|Feature|HGVSc|HGVSp|HGVSg|HGVS_OFFSET|STRAND|ClinVar|ClinVar_CLNSIG|ClinVar_CLNSIGCONF|ClinVar_CLNDN|gnomADg_AC|gnomADg_AN|gnomADg_AF|gnomADe_AC|gnomADe_AN|gnomADe_AF|gnomADe_Hom|SpliceAI_pred_DS_AG|SpliceAI_pred_DS_AL|SpliceAI_pred_DS_DG|SpliceAI_pred_DS_DL|SpliceAI_pred_DP_AG|SpliceAI_pred_DP_AL|SpliceAI_pred_DP_DG|SpliceAI_pred_DP_DL|REVEL|Mastermind_MMID3|CADD_PHRED">
1	8073919	.	C	T	100	PASS	DP=609;CSQ=T|ERRFI1|missense_variant|MODERATE|4/4||NM_018948.4|NM_018948.4:c.740G>A|NP_061821.1:p.Arg247Lys|1:g.8073919C>T||-1|||||7|30966|0.000226054|57|246130|0.000231585|0|0.00|0.00|0.00|0.00|-21|16|-3|-49|0.249|ERRFI1:R247K|25.6	GT:GQ:AD:DP:VF:NL:SB:NC:US:AQ:LQ	0/1:100:318,289:609:0.47455:30:-100:0.0256:35,47,28,48,59,72,82,96,53,114,107,157:100:100
```

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)* status: all files reviewed, 7 unresolved discussions (waiting on @Aisha-D)

___
*[`tso500_vep_config_v1.2.0.json` line 103 at r1](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16#-Ng-nFV73ZLpKKwEQ-u7:-NgP4gcr0vHlrbJi6Xju:btdqej1) ([raw file](https://github.com/eastgenomics/eggd_vep_helios_config/blob/a3c12d60c5c36e0ddb8ffd46bbc60de6325b45dc/tso500_vep_config_v1.2.0.json#L103)):*
<details><summary><i>Previously, Aisha-D (Aisha) wrote…</i></summary><blockquote>

Well.... when comparing this branch to the last release on vep 105 - everything but clinvar matched: https://github.com/eastgenomics/eggd_vep_helios_config/compare/v1.0.2...URA-337-helios-vep-config-v-1-2-0

On top of that, there appears to be no CADD 105 on dnanexus: https://platform.dnanexus.com/projects/Fkb6Gkj433GVVvj73J7x8KbV/data/assets/vep/vep_docker_v105.0

So it seems 104 was always used and it does populate data:
</blockquote></details>

Aisha checked this further here: https://cuhbioinformatics.atlassian.net/wiki/spaces/URA/pages/3008200934/231009+-+VEP+104

Working as intended, okay to proceed

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)* status: all files reviewed, 6 unresolved discussions (waiting on @Aisha-D)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)* status: all files reviewed, 6 unresolved discussions (waiting on @Aisha-D)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/eggd_vep_helios_config/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Aisha-D)

**Pull request merged**
